[package]
name = "lab5_2"
version = "0.1.0"
edition = "2021"
description = "Лабораторная работа № 5. Вариант 4. Задание 2."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"